// Generated from ESPN's public team API (site.api.espn.com) — ids, names,
// abbreviations and brand colors. Conference membership reflects 2024+
// realignment (Notre Dame listed under ACC as its affiliate home).
import type { Conference, Team } from '../types';

export const TEAMS: readonly Team[] = [
  {"id":"alabama","espnId":"333","school":"Alabama","mascot":"Crimson Tide","abbrev":"ALA","conference":"SEC","primary":"#9e1b32","secondary":"#ffffff"},
  {"id":"arkansas","espnId":"8","school":"Arkansas","mascot":"Razorbacks","abbrev":"ARK","conference":"SEC","primary":"#a32136","secondary":"#ffffff"},
  {"id":"auburn","espnId":"2","school":"Auburn","mascot":"Tigers","abbrev":"AUB","conference":"SEC","primary":"#002b5c","secondary":"#f26522"},
  {"id":"florida","espnId":"57","school":"Florida","mascot":"Gators","abbrev":"FLA","conference":"SEC","primary":"#0021a5","secondary":"#fa4616"},
  {"id":"georgia","espnId":"61","school":"Georgia","mascot":"Bulldogs","abbrev":"UGA","conference":"SEC","primary":"#ba0c2f","secondary":"#2c2a29"},
  {"id":"kentucky","espnId":"96","school":"Kentucky","mascot":"Wildcats","abbrev":"UK","conference":"SEC","primary":"#0033a0","secondary":"#ffffff"},
  {"id":"lsu","espnId":"99","school":"LSU","mascot":"Tigers","abbrev":"LSU","conference":"SEC","primary":"#461d76","secondary":"#fdd023"},
  {"id":"mississippi-state","espnId":"344","school":"Mississippi State","mascot":"Bulldogs","abbrev":"MSST","conference":"SEC","primary":"#5d1725","secondary":"#c1c6c8"},
  {"id":"missouri","espnId":"142","school":"Missouri","mascot":"Tigers","abbrev":"MIZ","conference":"SEC","primary":"#f1b82d","secondary":"#000000"},
  {"id":"oklahoma","espnId":"201","school":"Oklahoma","mascot":"Sooners","abbrev":"OU","conference":"SEC","primary":"#990000","secondary":"#ffffff"},
  {"id":"ole-miss","espnId":"145","school":"Ole Miss","mascot":"Rebels","abbrev":"MISS","conference":"SEC","primary":"#13294b","secondary":"#cf142b"},
  {"id":"south-carolina","espnId":"2579","school":"South Carolina","mascot":"Gamecocks","abbrev":"SC","conference":"SEC","primary":"#73000a","secondary":"#000000"},
  {"id":"tennessee","espnId":"2633","school":"Tennessee","mascot":"Volunteers","abbrev":"TENN","conference":"SEC","primary":"#ff8200","secondary":"#ffffff"},
  {"id":"texas","espnId":"251","school":"Texas","mascot":"Longhorns","abbrev":"TEX","conference":"SEC","primary":"#bf5700","secondary":"#ffffff"},
  {"id":"texas-a-m","espnId":"245","school":"Texas A&M","mascot":"Aggies","abbrev":"TA&M","conference":"SEC","primary":"#500000","secondary":"#ffffff"},
  {"id":"vanderbilt","espnId":"238","school":"Vanderbilt","mascot":"Commodores","abbrev":"VAN","conference":"SEC","primary":"#000000","secondary":"#cfae70"},
  {"id":"illinois","espnId":"356","school":"Illinois","mascot":"Fighting Illini","abbrev":"ILL","conference":"Big Ten","primary":"#ff5f05","secondary":"#13294b"},
  {"id":"indiana","espnId":"84","school":"Indiana","mascot":"Hoosiers","abbrev":"IU","conference":"Big Ten","primary":"#970310","secondary":"#ffffff"},
  {"id":"iowa","espnId":"2294","school":"Iowa","mascot":"Hawkeyes","abbrev":"IOWA","conference":"Big Ten","primary":"#231f20","secondary":"#fcd116"},
  {"id":"maryland","espnId":"120","school":"Maryland","mascot":"Terrapins","abbrev":"MD","conference":"Big Ten","primary":"#ce1126","secondary":"#ffffff"},
  {"id":"michigan","espnId":"130","school":"Michigan","mascot":"Wolverines","abbrev":"MICH","conference":"Big Ten","primary":"#00274c","secondary":"#ffcb05"},
  {"id":"michigan-state","espnId":"127","school":"Michigan State","mascot":"Spartans","abbrev":"MSU","conference":"Big Ten","primary":"#173f35","secondary":"#ffffff"},
  {"id":"minnesota","espnId":"135","school":"Minnesota","mascot":"Golden Gophers","abbrev":"MINN","conference":"Big Ten","primary":"#5e0a2f","secondary":"#fab41c"},
  {"id":"nebraska","espnId":"158","school":"Nebraska","mascot":"Cornhuskers","abbrev":"NEB","conference":"Big Ten","primary":"#e31937","secondary":"#ffffff"},
  {"id":"northwestern","espnId":"77","school":"Northwestern","mascot":"Wildcats","abbrev":"NU","conference":"Big Ten","primary":"#492f92","secondary":"#ffffff"},
  {"id":"ohio-state","espnId":"194","school":"Ohio State","mascot":"Buckeyes","abbrev":"OSU","conference":"Big Ten","primary":"#ba0c2f","secondary":"#a8adb4"},
  {"id":"oregon","espnId":"2483","school":"Oregon","mascot":"Ducks","abbrev":"ORE","conference":"Big Ten","primary":"#00934b","secondary":"#fff41b"},
  {"id":"penn-state","espnId":"213","school":"Penn State","mascot":"Nittany Lions","abbrev":"PSU","conference":"Big Ten","primary":"#061440","secondary":"#ffffff"},
  {"id":"purdue","espnId":"2509","school":"Purdue","mascot":"Boilermakers","abbrev":"PUR","conference":"Big Ten","primary":"#ceb888","secondary":"#000000"},
  {"id":"rutgers","espnId":"164","school":"Rutgers","mascot":"Scarlet Knights","abbrev":"RUTG","conference":"Big Ten","primary":"#ce0e2d","secondary":"#ffffff"},
  {"id":"ucla","espnId":"26","school":"UCLA","mascot":"Bruins","abbrev":"UCLA","conference":"Big Ten","primary":"#2774ae","secondary":"#f2a900"},
  {"id":"usc","espnId":"30","school":"USC","mascot":"Trojans","abbrev":"USC","conference":"Big Ten","primary":"#9d2235","secondary":"#ffc72c"},
  {"id":"washington","espnId":"264","school":"Washington","mascot":"Huskies","abbrev":"WASH","conference":"Big Ten","primary":"#33006f","secondary":"#e8d3a2"},
  {"id":"wisconsin","espnId":"275","school":"Wisconsin","mascot":"Badgers","abbrev":"WIS","conference":"Big Ten","primary":"#a00000","secondary":"#ffffff"},
  {"id":"arizona","espnId":"12","school":"Arizona","mascot":"Wildcats","abbrev":"ARIZ","conference":"Big 12","primary":"#cc0033","secondary":"#003366"},
  {"id":"arizona-state","espnId":"9","school":"Arizona State","mascot":"Sun Devils","abbrev":"ASU","conference":"Big 12","primary":"#ffc627","secondary":"#8c1d40"},
  {"id":"baylor","espnId":"239","school":"Baylor","mascot":"Bears","abbrev":"BAY","conference":"Big 12","primary":"#154734","secondary":"#ffb81c"},
  {"id":"byu","espnId":"252","school":"BYU","mascot":"Cougars","abbrev":"BYU","conference":"Big 12","primary":"#0047ba","secondary":"#002e5d"},
  {"id":"ucf","espnId":"2116","school":"UCF","mascot":"Knights","abbrev":"UCF","conference":"Big 12","primary":"#000000","secondary":"#b4a169"},
  {"id":"cincinnati","espnId":"2132","school":"Cincinnati","mascot":"Bearcats","abbrev":"CIN","conference":"Big 12","primary":"#000000","secondary":"#e00122"},
  {"id":"colorado","espnId":"38","school":"Colorado","mascot":"Buffaloes","abbrev":"COLO","conference":"Big 12","primary":"#cfb87c","secondary":"#000000"},
  {"id":"houston","espnId":"248","school":"Houston","mascot":"Cougars","abbrev":"HOU","conference":"Big 12","primary":"#c8102e","secondary":"#ffffff"},
  {"id":"iowa-state","espnId":"66","school":"Iowa State","mascot":"Cyclones","abbrev":"ISU","conference":"Big 12","primary":"#ae192d","secondary":"#ffc72a"},
  {"id":"kansas","espnId":"2305","school":"Kansas","mascot":"Jayhawks","abbrev":"KU","conference":"Big 12","primary":"#0051ba","secondary":"#e8000d"},
  {"id":"kansas-state","espnId":"2306","school":"Kansas State","mascot":"Wildcats","abbrev":"KSU","conference":"Big 12","primary":"#330a57","secondary":"#e2e3e4"},
  {"id":"oklahoma-state","espnId":"197","school":"Oklahoma State","mascot":"Cowboys","abbrev":"OKST","conference":"Big 12","primary":"#fe5c00","secondary":"#000000"},
  {"id":"tcu","espnId":"2628","school":"TCU","mascot":"Horned Frogs","abbrev":"TCU","conference":"Big 12","primary":"#4d1979","secondary":"#ffffff"},
  {"id":"texas-tech","espnId":"2641","school":"Texas Tech","mascot":"Red Raiders","abbrev":"TTU","conference":"Big 12","primary":"#da291c","secondary":"#000000"},
  {"id":"utah","espnId":"254","school":"Utah","mascot":"Utes","abbrev":"UTAH","conference":"Big 12","primary":"#be0000","secondary":"#ffffff"},
  {"id":"west-virginia","espnId":"277","school":"West Virginia","mascot":"Mountaineers","abbrev":"WVU","conference":"Big 12","primary":"#eaaa00","secondary":"#002855"},
  {"id":"boston-college","espnId":"103","school":"Boston College","mascot":"Eagles","abbrev":"BC","conference":"ACC","primary":"#8c2232","secondary":"#dbcca6"},
  {"id":"california","espnId":"25","school":"California","mascot":"Golden Bears","abbrev":"CAL","conference":"ACC","primary":"#041e42","secondary":"#ffc72c"},
  {"id":"clemson","espnId":"228","school":"Clemson","mascot":"Tigers","abbrev":"CLEM","conference":"ACC","primary":"#f56600","secondary":"#ffffff"},
  {"id":"duke","espnId":"150","school":"Duke","mascot":"Blue Devils","abbrev":"DUKE","conference":"ACC","primary":"#00539b","secondary":"#ffffff"},
  {"id":"florida-state","espnId":"52","school":"Florida State","mascot":"Seminoles","abbrev":"FSU","conference":"ACC","primary":"#782f40","secondary":"#ceb888"},
  {"id":"georgia-tech","espnId":"59","school":"Georgia Tech","mascot":"Yellow Jackets","abbrev":"GT","conference":"ACC","primary":"#b3a369","secondary":"#ffffff"},
  {"id":"louisville","espnId":"97","school":"Louisville","mascot":"Cardinals","abbrev":"LOU","conference":"ACC","primary":"#c9001f","secondary":"#ffffff"},
  {"id":"miami","espnId":"2390","school":"Miami","mascot":"Hurricanes","abbrev":"MIA","conference":"ACC","primary":"#f47423","secondary":"#035131"},
  {"id":"north-carolina","espnId":"153","school":"North Carolina","mascot":"Tar Heels","abbrev":"UNC","conference":"ACC","primary":"#7bafd4","secondary":"#13294b"},
  {"id":"nc-state","espnId":"152","school":"NC State","mascot":"Wolfpack","abbrev":"NCSU","conference":"ACC","primary":"#cc0000","secondary":"#ffffff"},
  {"id":"pittsburgh","espnId":"221","school":"Pittsburgh","mascot":"Panthers","abbrev":"PITT","conference":"ACC","primary":"#003594","secondary":"#ffb81c"},
  {"id":"smu","espnId":"2567","school":"SMU","mascot":"Mustangs","abbrev":"SMU","conference":"ACC","primary":"#a80000","secondary":"#0033a1"},
  {"id":"stanford","espnId":"24","school":"Stanford","mascot":"Cardinal","abbrev":"STAN","conference":"ACC","primary":"#8c1515","secondary":"#ffffff"},
  {"id":"syracuse","espnId":"183","school":"Syracuse","mascot":"Orange","abbrev":"SYR","conference":"ACC","primary":"#000e54","secondary":"#ff431b"},
  {"id":"virginia","espnId":"258","school":"Virginia","mascot":"Cavaliers","abbrev":"UVA","conference":"ACC","primary":"#232d4b","secondary":"#f84c1e"},
  {"id":"virginia-tech","espnId":"259","school":"Virginia Tech","mascot":"Hokies","abbrev":"VT","conference":"ACC","primary":"#6a2c3e","secondary":"#cf4520"},
  {"id":"wake-forest","espnId":"154","school":"Wake Forest","mascot":"Demon Deacons","abbrev":"WAKE","conference":"ACC","primary":"#ceb888","secondary":"#2c2a29"},
  {"id":"notre-dame","espnId":"87","school":"Notre Dame","mascot":"Fighting Irish","abbrev":"ND","conference":"ACC","primary":"#062340","secondary":"#c99700"}
] as const;

export const CONFERENCES: readonly Conference[] = ['SEC', 'Big Ten', 'Big 12', 'ACC'] as const;

/** Official team logo (ESPN CDN). Pieces fall back to a monogram if offline. */
export function logoUrl(team: Team): string {
  return `https://a.espncdn.com/i/teamlogos/ncaa/500/${team.espnId}.png`;
}

export function teamById(id: string): Team {
  return TEAMS.find((t) => t.id === id) ?? TEAMS.find((t) => t.id === 'tennessee')!;
}

/** Well-known home venues; anything missing falls back to "<School> Stadium". */
const VENUES: Record<string, string> = {
  tennessee: 'Neyland Stadium',
  alabama: 'Bryant–Denny Stadium',
  georgia: 'Sanford Stadium',
  lsu: 'Tiger Stadium',
  florida: 'Ben Hill Griffin Stadium',
  auburn: 'Jordan–Hare Stadium',
  'texas-a-m': 'Kyle Field',
  texas: 'DKR–Texas Memorial Stadium',
  oklahoma: 'Oklahoma Memorial Stadium',
  arkansas: 'Razorback Stadium',
  'south-carolina': 'Williams–Brice Stadium',
  kentucky: 'Kroger Field',
  'ole-miss': 'Vaught–Hemingway Stadium',
  'mississippi-state': 'Davis Wade Stadium',
  missouri: 'Faurot Field',
  vanderbilt: 'FirstBank Stadium',
  michigan: 'Michigan Stadium',
  'ohio-state': 'Ohio Stadium',
  'penn-state': 'Beaver Stadium',
  wisconsin: 'Camp Randall Stadium',
  nebraska: 'Memorial Stadium',
  iowa: 'Kinnick Stadium',
  'michigan-state': 'Spartan Stadium',
  minnesota: 'Huntington Bank Stadium',
  illinois: 'Memorial Stadium',
  indiana: 'Memorial Stadium',
  purdue: 'Ross–Ade Stadium',
  northwestern: 'Ryan Field',
  maryland: 'SECU Stadium',
  rutgers: 'SHI Stadium',
  ucla: 'Rose Bowl',
  usc: 'LA Memorial Coliseum',
  washington: 'Husky Stadium',
  oregon: 'Autzen Stadium',
  'notre-dame': 'Notre Dame Stadium',
  clemson: 'Memorial Stadium',
  'florida-state': 'Doak Campbell Stadium',
  miami: 'Hard Rock Stadium',
  'north-carolina': 'Kenan Stadium',
  'nc-state': 'Carter–Finley Stadium',
  duke: 'Wallace Wade Stadium',
  'virginia-tech': 'Lane Stadium',
  virginia: 'Scott Stadium',
  'georgia-tech': 'Bobby Dodd Stadium',
  louisville: 'Cardinal Stadium',
  pittsburgh: 'Acrisure Stadium',
  syracuse: 'JMA Wireless Dome',
  'boston-college': 'Alumni Stadium',
  'wake-forest': 'Allegacy Stadium',
  stanford: 'Stanford Stadium',
  california: 'California Memorial Stadium',
  smu: 'Gerald J. Ford Stadium',
  byu: 'LaVell Edwards Stadium',
  utah: 'Rice–Eccles Stadium',
  colorado: 'Folsom Field',
  arizona: 'Arizona Stadium',
  'arizona-state': 'Mountain America Stadium',
  baylor: 'McLane Stadium',
  tcu: 'Amon G. Carter Stadium',
  'texas-tech': 'Jones AT&T Stadium',
  'oklahoma-state': 'Boone Pickens Stadium',
  kansas: 'Kansas Memorial Stadium',
  'kansas-state': 'Bill Snyder Family Stadium',
  'iowa-state': 'Jack Trice Stadium',
  'west-virginia': 'Milan Puskar Stadium',
  cincinnati: 'Nippert Stadium',
  ucf: 'FBC Mortgage Stadium',
  houston: 'TDECU Stadium',
};

export function venueFor(team: Team): string {
  return VENUES[team.id] ?? `${team.school} Stadium`;
}

/** A team's primary helmet look: shell, center stripe, facemask. */
export interface HelmetSpec {
  shell: string;
  stripe: string;
  mask: string;
  /** Michigan-style winged helmet. */
  wing?: boolean;
}

// Approximations of each program's real primary helmet. Teams not listed
// fall back to primary shell + secondary stripe/mask.
const HELMETS: Record<string, Partial<HelmetSpec>> = {
  alabama: { shell: '#9e1b32', stripe: '#ffffff', mask: '#8a8d8f' },
  arkansas: { shell: '#a32136', stripe: '#ffffff', mask: '#a32136' },
  auburn: { shell: '#ffffff', stripe: '#002b5c', mask: '#002b5c' },
  florida: { shell: '#fa4616', stripe: '#0021a5', mask: '#0021a5' },
  georgia: { shell: '#ba0c2f', stripe: '#000000', mask: '#ba0c2f' },
  kentucky: { shell: '#0033a0', stripe: '#ffffff', mask: '#ffffff' },
  lsu: { shell: '#fdd023', stripe: '#461d76', mask: '#fdd023' },
  'mississippi-state': { shell: '#5d1725', stripe: '#ffffff', mask: '#5d1725' },
  missouri: { shell: '#f1b82d', stripe: '#000000', mask: '#000000' },
  oklahoma: { shell: '#990000', stripe: '#ffffff', mask: '#ffffff' },
  'ole-miss': { shell: '#13294b', stripe: '#cf142b', mask: '#cf142b' },
  'south-carolina': { shell: '#73000a', stripe: '#ffffff', mask: '#73000a' },
  tennessee: { shell: '#ffffff', stripe: '#ff8200', mask: '#ffffff' },
  texas: { shell: '#ffffff', stripe: '#bf5700', mask: '#8a8d8f' },
  'texas-a-m': { shell: '#500000', stripe: '#ffffff', mask: '#500000' },
  vanderbilt: { shell: '#000000', stripe: '#cfae70', mask: '#ffffff' },
  illinois: { shell: '#ff5f05', stripe: '#13294b', mask: '#13294b' },
  indiana: { shell: '#970310', stripe: '#ffffff', mask: '#ffffff' },
  iowa: { shell: '#231f20', stripe: '#fcd116', mask: '#fcd116' },
  maryland: { shell: '#ffffff', stripe: '#ce1126', mask: '#ce1126' },
  michigan: { shell: '#00274c', stripe: '#ffcb05', mask: '#8a8d8f', wing: true },
  'michigan-state': { shell: '#173f35', stripe: '#ffffff', mask: '#ffffff' },
  minnesota: { shell: '#5e0a2f', stripe: '#fab41c', mask: '#fab41c' },
  nebraska: { shell: '#ffffff', stripe: '#e31937', mask: '#e31937' },
  northwestern: { shell: '#492f92', stripe: '#ffffff', mask: '#ffffff' },
  'ohio-state': { shell: '#c5c8cc', stripe: '#ba0c2f', mask: '#8a8d8f' },
  oregon: { shell: '#00934b', stripe: '#fff41b', mask: '#fff41b' },
  'penn-state': { shell: '#ffffff', stripe: '#061440', mask: '#8a8d8f' },
  purdue: { shell: '#ceb888', stripe: '#000000', mask: '#000000' },
  rutgers: { shell: '#ce0e2d', stripe: '#ffffff', mask: '#ffffff' },
  ucla: { shell: '#2774ae', stripe: '#f2a900', mask: '#f2a900' },
  usc: { shell: '#9d2235', stripe: '#ffc72c', mask: '#ffc72c' },
  washington: { shell: '#33006f', stripe: '#e8d3a2', mask: '#e8d3a2' },
  wisconsin: { shell: '#ffffff', stripe: '#a00000', mask: '#a00000' },
  arizona: { shell: '#003366', stripe: '#cc0033', mask: '#cc0033' },
  'arizona-state': { shell: '#8c1d40', stripe: '#ffc627', mask: '#ffc627' },
  baylor: { shell: '#154734', stripe: '#ffb81c', mask: '#ffb81c' },
  byu: { shell: '#0047ba', stripe: '#ffffff', mask: '#ffffff' },
  ucf: { shell: '#000000', stripe: '#b4a169', mask: '#b4a169' },
  cincinnati: { shell: '#000000', stripe: '#e00122', mask: '#e00122' },
  colorado: { shell: '#cfb87c', stripe: '#000000', mask: '#000000' },
  houston: { shell: '#c8102e', stripe: '#ffffff', mask: '#ffffff' },
  'iowa-state': { shell: '#ae192d', stripe: '#ffc72a', mask: '#ffc72a' },
  kansas: { shell: '#0051ba', stripe: '#e8000d', mask: '#e8000d' },
  'kansas-state': { shell: '#c5c8cc', stripe: '#330a57', mask: '#330a57' },
  'oklahoma-state': { shell: '#fe5c00', stripe: '#000000', mask: '#000000' },
  tcu: { shell: '#4d1979', stripe: '#ffffff', mask: '#ffffff' },
  'texas-tech': { shell: '#000000', stripe: '#da291c', mask: '#da291c' },
  utah: { shell: '#be0000', stripe: '#ffffff', mask: '#ffffff' },
  california: { shell: '#041e42', stripe: '#ffc72c', mask: '#ffc72c' },
  clemson: { shell: '#f56600', stripe: '#ffffff', mask: '#ffffff' },
  duke: { shell: '#ffffff', stripe: '#00539b', mask: '#00539b' },
  'florida-state': { shell: '#782f40', stripe: '#ceb888', mask: '#ceb888' },
  'georgia-tech': { shell: '#b3a369', stripe: '#ffffff', mask: '#ffffff' },
  louisville: { shell: '#ad0000', stripe: '#ffffff', mask: '#ffffff' },
  miami: { shell: '#ffffff', stripe: '#f47423', mask: '#035131' },
  'north-carolina': { shell: '#7bafd4', stripe: '#ffffff', mask: '#ffffff' },
  'nc-state': { shell: '#cc0000', stripe: '#ffffff', mask: '#ffffff' },
  pittsburgh: { shell: '#003594', stripe: '#ffb81c', mask: '#ffb81c' },
  smu: { shell: '#cc0035', stripe: '#0039a6', mask: '#ffffff' },
  stanford: { shell: '#8c1515', stripe: '#ffffff', mask: '#ffffff' },
  syracuse: { shell: '#f76900', stripe: '#ffffff', mask: '#ffffff' },
  virginia: { shell: '#002f6c', stripe: '#e57200', mask: '#ffffff' },
  'virginia-tech': { shell: '#630031', stripe: '#cf4420', mask: '#cf4420' },
  'wake-forest': { shell: '#000000', stripe: '#9e7e38', mask: '#9e7e38' },
  'notre-dame': { shell: '#c99700', stripe: '#c99700', mask: '#8a8d8f' },
};

export function helmetFor(team: Team): HelmetSpec {
  return { shell: team.primary, stripe: team.secondary, mask: team.secondary, ...HELMETS[team.id] };
}
